# Make sure to recreate the docker image after changing
# this file:
#
#     cd wingolfsplattform-docker
#     make rebuild_test
#     make test
#
source 'https://rubygems.org' do

  gem 'cucumber'
  gem 'capybara'
  gem 'selenium-webdriver'
  gem 'pry'

end